---
permalink: install-setup/afx-cable-overview.html 
sidebar: sidebar 
keywords: afx, afx 1k, cable, overview, cisco 9332, cisco 9364, cabling, hardware, switches, storage shelves, disk shelves, controller nodes 
summary: コントローラー ノードをネットワーク、スイッチ、ストレージ シェルフにケーブル接続する方法を学習します。 
---
= AFX 1K ストレージシステムでサポートされている構成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
適切なシステム セットアップに必要な互換性のあるストレージ ディスク シェルフ、スイッチ、ケーブル タイプなど、AFX 1K ストレージ システムでサポートされているハードウェア コンポーネントとケーブル オプションについて説明します。



== サポートされているAFX 1Kケーブル構成

AFX 1K ストレージ システムの初期構成では、デュアル スイッチを介してストレージ ディスク シェルフに接続された少なくとも 4 つのコントローラー ノードがサポートされます。

追加のコントローラー ノードとディスク シェルフにより、初期の AFX 1K ストレージ システム構成が拡張されます。拡張された AFX 1K 構成は、以下に示すスキーマと同じスイッチベースのケーブル接続方法に従います。

image:../media/drw_afx_cable_overview_half_node_ieops-2358.svg["AFK 1K ストレージシステムのケーブル接続例"]



== サポートされているハードウェアコンポーネント

AFX 1K ストレージ システムと互換性のあるストレージ ディスク シェルフ、スイッチ、およびケーブル タイプを確認します。

[cols="2,2,3,6"]
|===
| *コントローラーシェルフ* | *ディスクシェルフ* | *サポートされているスイッチ* | *対応ケーブル* 


 a| 
AFX 1K
 a| 
NX224
 a| 
* Cisco Nexus 9332D-GX2B (400GbE)
* Cisco Nexus 9364D-GX2A (400GbE)

 a| 
* 400GbE QSFP-DDブレークアウトから4x100GbE QSFPブレークアウトケーブル
+

NOTE: ブレークアウト ケーブルは、スイッチ、コントローラー、ディスク シェルフ間の 100GbE 接続に使用されます。

+
** コントローラ クラスタと HA ポートへの 100GbE ケーブル
** ディスクシェルフへの100GbEケーブル


* スイッチ A とスイッチ B 間の ISL 接続用の 2 x 400GbE ケーブル
* 管理接続用のRJ-45ケーブル


|===
.次の手順
サポートされているシステム構成とハードウェアコンポーネントを確認した後、link:install-network-reqs.html["AFX 1K ストレージシステムのネットワーク要件を確認します"] 。
