---
sidebar: sidebar 
permalink: install-setup/cluster-setup.html 
keywords: afx, afx system, cluster setup, setup 
summary: AFX ハードウェアをインストールしたら、クラスターのセットアップを完了できます。このプロセスには、順番に実行する必要がある 2 つの関連する構成フェーズが含まれます。 
---
= AFXストレージシステムのONTAPクラスタをセットアップする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFX ハードウェアをインストールしたら、 ONTAPクラスターのセットアップを完了できます。このプロセスには、順番に実行する必要がある 2 つの関連する構成フェーズが含まれます。



== 初期クラスタ設定を実行する

ラップトップ デバイスを AFX クラスターに接続し、いくつかのグローバル構成値を設定できます。

.タスク概要
AFX クラスターには、最初に構成する必要がある 4 つの領域があります。最初の 3 つは必須ですが、最後の 1 つはオプションです。

.開始する前に
以下の情報が必要です:

* クラスタ管理IPアドレス
+
クラスタ管理 IP アドレスは、クラスタ管理者が管理 SVM にアクセスしてクラスタを管理するために使用するクラスタ管理インターフェイスの一意の IPv4 アドレスです。このIPアドレスは、組織内でIPアドレスの割り当てを担当している管理者から取得できます。

* ネットワーク サブネット マスク
+
クラスタのセットアップ中に、 ONTAPでは構成に適したネットワーク インターフェイスのセットが必要になります。必要に応じて推奨事項を調整できます。



以下のものも必要になります:

* ネットワーク ゲートウェイのIPアドレス
* DNSドメイン名
* DNSネームサーバーのIPアドレス
* NTPサーバーのIPアドレス
* サブネット マスク


.手順
. クラスター ネットワークを検出します。
+
.. ラップトップを管理スイッチに接続し、ネットワーク コンピューターおよびデバイスにアクセスします。
.. ファイルエクスプローラーを開きます。
.. *ネットワーク*を選択し、右クリックして*更新*を選択します。
.. いずれかのONTAPアイコンを選択し、画面に表示される証明書をすべて受け入れます。
+
システム マネージャーのユーザー インターフェイスが表示されます。



. 管理者パスワードを設定します。
+
パスワードを入力して確認します `admin`アカウント。*続行*を選択します。

. クラスターとコントローラー ノードの IP アドレスを構成します。
+
IP アドレスとサブネット マスクを指定します。

. ネットワーク サービスを構成します。*続行*を選択します。
+
DNS サーバーと NTP サーバーの詳細を定義します。

. 必要に応じて暗号化を設定します。
+
クラスター暗号化の詳細を定義できます。*続行*を選択します。



.次の手順
システム マネージャーのサインイン ページにリダイレクトされます。で説明されている手順を実行します。<<クラスターのセットアップを完了する>> 。



== クラスターのセットアップを完了する

初期設定が完了したら、System Manager を使用してONTAPクラスタのセットアップを完了できます。

.タスク概要
セットアップ中に構成される AFX システムONTAPクラスタには 3 つの領域があります。可能であれば 3 つすべてを完了してください。ただし、必須なのは最初の 1 つだけです。

.開始する前に
以下の情報が必要です:

* VLAN 構成の詳細。
* NAS および/または S3 の構成の詳細。


.手順
. クラスタの初期セットアップ時に指定した管理者アカウントを使用して、System Manager にSign in。右上のポップアップ ウィンドウに 3 つの構成オプションが表示されます。
. *VLAN とタグ付け*を選択し、環境に適したネットワーク オプションを選択します。
. *ネットワーク サービス* を選択し、デフォルトのデータ SVM のクライアント アクセス プロトコルを構成します。
. *データ コンテナ* を選択し、ボリュームまたは S3 バケットを作成します。


.次の手順
あなたがすべきlink:../get-started/prepare-cluster-admin.html["AFX投与の準備"]AFX クラスターを本番環境で使用する前に。

.関連情報
* link:../administer/configure-svm.html["AFX SVMを構成する"]
* link:../get-started/prepare-cluster-admin.html["AFX投与の準備"]

