---
sidebar: sidebar 
permalink: install-setup/cluster-setup.html 
keywords: afx, afx system, cluster setup, setup 
summary: AFXハードウェアのインストールが完了したら、ONTAPクラスタのセットアップを完了できます。このプロセスには、順番に実行する必要がある関連する構成フェーズが含まれます。この一環として、オプションでAI Data Engine（AIDE）を実行するデータ コンピューティング ノード（DCN）を追加できます。これにより、AFXストレージ クラスタとDCNクラスタが、同じONTAPコントロール プレーンを通じて管理される単一のシステムとして動作できるようになります。 
---
= AFXストレージシステムのONTAPクラスタをセットアップする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFXハードウェアのインストールが完了したら、ONTAPクラスタのセットアップを完了できます。このプロセスには、順番に実行する必要がある関連する構成フェーズが含まれます。この一環として、オプションでAI Data Engine（AIDE）を実行するデータ コンピューティング ノード（DCN）を追加できます。これにより、AFXストレージ クラスタとDCNクラスタが、同じONTAPコントロール プレーンを通じて管理される単一のシステムとして動作できるようになります。



== AFXストレージシステムのセットアップの準備

ONTAPクラスターを設定する前に、コアAFX要件と追加のAIDEに関する考慮事項を確認して、セットアップ プロセスを正常に完了するために必要なすべての情報とリソースが揃っていることを確認する必要があります。



=== コアAFX要件

AFX クラスターをセットアップする際には、考慮すべきコア要件がいくつかあります。

.ハードウェアのインストール
AFX システムのハードウェアのインストールが完了していることを確認してください。詳細については、link:../install-setup/install-setup-workflow.html["AFXシステムをインストールする"]を参照してください。

.基本的な IP アドレス指定
次の IP アドレス構成が必要です：

* クラスタ管理IPアドレス
+
クラスタ管理 IP アドレスは、クラスタ管理者が管理 SVM にアクセスしてクラスタを管理するために使用するクラスタ管理インターフェイスの一意の IPv4 アドレスです。このIPアドレスは、組織内でIPアドレスの割り当てを担当している管理者から取得できます。

* ネットワーク サブネット マスク
+
クラスタのセットアップ中に、 ONTAPでは構成に適したネットワーク インターフェイスのセットが必要になります。必要に応じて推奨事項を調整できます。



.追加のネットワーク構成
次の関連するネットワーク情報も必要になります：

* ネットワーク ゲートウェイのIPアドレス
* DNSドメイン名
* DNSネームサーバーのIPアドレス
* NTPサーバーのIPアドレス
* サブネット マスク




=== 追加のAIDE考慮事項

AFXを初めてインストールおよびセットアップする際に、オプションでNetApp AI Data Engine（AIDE）を含めることができます。AIDEは2つのデプロイメントモデルをサポートしています：サードパーティサーバー上のAIDEソフトウェアまたはNetApp提供のデータコンピュートノード（DCN）。AIDEのセットアップを計画している場合は、まずデプロイメントモデルの前提条件を完了してください：

* サードパーティ製サーバーの展開については、 https://docs.netapp.com/us-en/ai-data-engine/install-aide-server/aide-mde-server-hardware-requirements.html["サードパーティのサーバー上のAI Data Engineのハードウェアインストール"^]を完了してから、 https://docs.netapp.com/us-en/ai-data-engine/install-setup/install-aide-as-software.html["サードパーティサーバーにAIDEソフトウェアをインストールする"^]を実行してください。
* NetApp DCN 展開の場合は、完了してください https://docs.netapp.com/us-en/ai-data-engine/install-dcn/aide-dcn-hardware-requirements.html["NetApp提供のデータコンピュートノードへのAI Data Engineのハードウェアインストール"^]。
* 計算ノードのアドレスおよび関連するネットワーク構成を取得します。




== 初期クラスタ設定を実行する

ラップトップ デバイスを AFX クラスターに接続し、いくつかのグローバル構成値を設定できます。

.タスク概要
AFX クラスターには、最初に構成する必要がある 4 つの領域があります。最初の 3 つは必須ですが、最後の 1 つはオプションです。

.手順
. クラスター ネットワークを検出します。
+
.. ラップトップを管理スイッチに接続し、ネットワーク コンピューターおよびデバイスにアクセスします。
.. ファイルエクスプローラーを開きます。
.. *ネットワーク*を選択し、右クリックして*更新*を選択します。
.. いずれかのONTAPアイコンを選択し、画面に表示される証明書をすべて受け入れます。
+
システム マネージャーのユーザー インターフェイスが表示されます。



. 管理者パスワードを設定します。
+
パスワードを入力して確認します `admin`アカウント。*続行*を選択します。

. AFX クラスターとコントローラー ノードの IP アドレスを設定します。
+
IP アドレスとサブネット マスクを指定します。

. AFXストレージシステムでAI Data Engineをインストールする場合は、3つの計算ノードのIPアドレスを指定してください。
. DNS や NIS などのネットワーク サービスを構成します。*続行*を選択します。
+
DNS サーバーと NTP サーバーの詳細を定義します。

. 必要に応じて暗号化を設定します。
+
クラスター暗号化の詳細を定義できます。*続行*を選択します。

+

NOTE: Windows以外の環境でクラスタを作成する方法については、以下を参照してください。 link:https://docs.netapp.com/us-en/ontap/software_setup/setup-cluster.html["ONTAPクラスタを作成し、ノードを結合する"^]。



.次の手順
システム マネージャーのサインイン ページにリダイレクトされます。で説明されている手順を実行します。<<クラスターのセットアップを完了する>> 。



== クラスターのセットアップを完了する

初期設定が完了したら、System Manager を使用してONTAPクラスタのセットアップを完了できます。

.タスク概要
セットアップ中に構成される AFX システムONTAPクラスタには 3 つの領域があります。可能であれば 3 つすべてを完了してください。ただし、必須なのは最初の 1 つだけです。

.開始する前に
以下の情報が必要です:

* VLAN 構成の詳細。
* NAS および/または S3 の構成の詳細。


.手順
. クラスタの初期セットアップ時に指定した管理者アカウントを使用して、System Manager にSign in。右上のポップアップ ウィンドウに 3 つの構成オプションが表示されます。
. *VLAN とタグ付け*を選択し、環境に適したネットワーク オプションを選択します。
. *ネットワーク サービス* を選択し、デフォルトのデータ SVM のクライアント アクセス プロトコルを構成します。
. *データ コンテナ* を選択し、ボリュームまたは S3 バケットを作成します。


.次の手順
* AFXクラスタのセットアップの一環としてAIDEを含めた場合は、追加のAIDE設定手順を完了してください。認証設定はすべてのAIDEデプロイメントに適用されます。ライセンス版AIDE機能を使用するNetApp DCNデプロイメントにはライセンスが必要です。サードパーティサーバーのデプロイメントはメタデータに焦点を当てており、AIDEライセンスは必要ありません。詳細については、 https://docs.netapp.com/us-en/ai-data-engine/install-setup/cluster-setup-afx.html["AI Data Engineのセットアップ"^]を参照してください。
* あなたがすべきlink:../get-started/prepare-cluster-admin.html["AFX投与の準備"]AFX クラスターを本番環境で使用する前に。




== 関連情報

* link:../get-started/learn-about-aide.html["NetApp AI Data Engineについて学ぶ"]
* link:../administer/configure-svm.html["AFX SVMを構成する"]
* link:../get-started/prepare-cluster-admin.html["AFX投与の準備"]

