---
sidebar: sidebar 
permalink: install-setup/deploy-hardware.html 
keywords: afx, afx 1k, install, setup, hardware, deploy 
summary: AFX 1K ストレージ システムおよびストレージ シェルフ用のレール キットをインストールし、キャビネットまたは Telco ラックに AFX ハードウェアを固定する方法を説明します。 
---
= AFX 1Kストレージシステムをインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
スイッチをインストールした後、AFX 1K ストレージ システムのハードウェアをインストールする必要があります。まず、レールキットを取り付けます。次に、ストレージ システムをキャビネットまたは Telco ラックに設置して固定します。

.開始する前に
* レール キットに同梱されている説明書があることを確認してください。
* ストレージ システムとストレージ シェルフの重量に関連する安全上の懸念事項を理解します。
* ストレージ システムを通る空気の流れは、ベゼルまたはエンド キャップが取り付けられている前面から入り、ポートが配置されている背面から排出されることを理解してください。


.手順
. 必要に応じて、キットに付属の説明書に従って、ストレージ システムおよびストレージ シェルフ用のレール キットを取り付けます。
. コントローラをキャビネットまたは電話ラックに設置して固定します。
+
.. ストレージ システムをキャビネットまたは Telco ラックの中央のレールに配置し、ストレージ システムを下から支えて所定の位置にスライドさせます。
.. 付属の取り付けネジを使用して、ストレージ システムをキャビネットまたは Telco ラックに固定します。


. ベゼルをコントローラーの前面に取り付けます。
. AFX 1K ストレージ システムにケーブル管理デバイスが付属している場合は、それをストレージ システムの背面に取り付けます。
+
image::../media/drw_affa1k_install_cable_mgmt_ieops-1697.svg[ケーブル管理装置を設置する]

. 収納棚を取り付けて固定します。
+
.. 収納棚の背面をレール上に置き、棚を下から支えてキャビネットまたは Telco ラックにスライドさせます。
+
一般に、ストレージ シェルフとコントローラはスイッチの近くに設置する必要があります。複数のストレージ シェルフを設置する場合は、最初のストレージ シェルフをコントローラの真上に配置します。 2 番目のストレージ シェルフをコントローラーの真下に配置します。追加の保管棚についてもこのパターンを繰り返します。

.. 付属の取り付けネジを使用して、収納棚をキャビネットまたは電話ラックに固定します。




.次の手順
AFXシステムのハードウェアをインストールしたら、link:afx-cable-overview.html["AFX 1K ストレージシステムでサポートされているケーブル構成"] 。
