---
sidebar: sidebar 
permalink: install-setup/install-setup-requirements.html 
keywords: afx, afx 1k, install, setup, requirements, cautions 
summary: AFX 1K ストレージ コントローラーおよびストレージ シェルフに必要な機器と持ち上げる際の注意事項を確認します。 
---
= AFX 1K ストレージ システムのインストール要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFX 1K ストレージ コントローラーおよびストレージ シェルフに必要な機器と持ち上げる際の注意事項を確認します。



== インストールに必要な機器

AFX 1K ストレージ システムをインストールするには、次の機器とツールが必要です。

* ストレージシステムを構成するためのWebブラウザへのアクセス
* 静電気放電（ESD）ストラップ
* 懐中電灯
* USB/シリアル接続を備えたラップトップまたはコンソール
* 保管棚のIDを設定するためのペーパークリップまたは先端の細いボールペン
* No.2プラス ドライバ




== 持ち上げ時の注意事項

AFX ストレージ コントローラーとストレージ シェルフは重量があります。これらの品物を持ち上げたり移動したりするときには注意してください。



=== ストレージコントローラの重み

AFX 1K ストレージ コントローラーを移動または持ち上げる場合は、必要な予防措置を講じてください。

AFX 1K ストレージ コントローラーの重量は最大 62.83 ポンド (28.5 kg) になります。ストレージ コントローラを持ち上げるには、2 人または油圧リフトを使用してください。

image::../media/drw_a1k_weight_caution_ieops-1698.svg[ASA A1K 持ち上げ注意アイコン]



=== 収納棚の重量

棚を移動したり持ち上げたりするときは、必要な予防措置を講じてください。

.NX224シェルフ
--
NX224 シェルフの重量は最大 60.1 ポンド (27.3 kg) になります。棚を持ち上げるには、2 人または油圧リフトを使用してください。棚の重量が不均衡にならないように、すべてのコンポーネントを棚（前面と背面の両方）内に保管してください。

image::../media/drw_nx224_lifting_weight_ieops-2437.svg[NX224 NSM100 吊り上げ注意]

.関連情報
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["安全情報と規制に関する通知"^]


.次の手順
ハードウェア要件を確認したら、link:prepare-hardware.html["AFX 1Kストレージシステムのインストール準備"] 。

--