---
sidebar: sidebar 
permalink: secure-data/prepare-secure-data.html 
keywords: afx, afx system, prepare, prepare secure, prepare secure data 
summary: AFX データを管理する前に、主要な概念と機能について理解しておく必要があります。 
---
= AFXストレージシステムのデータを保護する準備
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFX データを管理する前に、主要な概念と機能について理解しておく必要があります。



== 用語とオプション

AFX データ セキュリティに関連して、知っておくべき用語がいくつかあります。

ランサムウェア:: ランサムウェアは、ファイルを暗号化してユーザーがアクセスできないようにする悪意のあるソフトウェアです。通常、データを復号化するには何らかの支払いが要求されます。  ONTAP は、Autonomous Ransomware Protection (ARP) などの機能を通じて、ランサムウェアから保護するソリューションを提供します。
暗号化:: 暗号化とは、適切な認証なしには簡単に読み取ることができない安全な形式にデータを変換するプロセスです。ONTAP は、保存中のデータを保護するために、ソフトウェア ベースとハードウェア ベースの両方の暗号化テクノロジを提供します。これにより、ストレージ メディアが再利用、返却、紛失、盗難された場合でも、読み取ることができなくなります。これらの暗号化ソリューションは、外部のキー管理サーバーまたはONTAPが提供するオンボード キー マネージャーを使用して管理できます。参照link:../secure-data/encrypt-data-at-rest.html["AFX ストレージ システムに保存されているデータを暗号化する"]詳細についてはこちらをご覧ください。
デジタル証明書とPKI:: デジタル証明書は、公開鍵の所有権を証明するために使用される電子文書です。公開キーと関連する秘密キーは、通常、TLS や IPsec などの大規模なセキュリティ フレームワークの一部として ID を確立するなど、さまざまな方法で使用できます。これらのキーと、それをサポートするプロトコルおよびフォーマット標準は、公開キー インフラストラクチャ (PKI) の基礎を形成します。参照link:../administer/manage-certificates.html#generate-a-certificate-signing-request["AFX ストレージ システム上の証明書を管理する"]詳細についてはこちらをご覧ください。
インターネットプロトコルセキュリティ:: IPsec は、IP レベルでネットワーク エンドポイント間を流れるトラフィックに対して、転送中のデータの暗号化、整合性、および認証を提供するインターネット標準です。  NFS や SMB などの上位レベルのプロトコルを含む、 ONTAPとクライアント間のすべての IP トラフィックを保護します。 IPsec は、データに対する悪意のあるリプレイ攻撃や中間者攻撃から保護します。参照link:../secure-data/secure-ip-connections.html["AFXストレージシステム上の安全なIP接続"]詳細についてはこちらをご覧ください。




== 関連情報

* link:../administer/additional-ontap-svm.html["追加のAFX SVM管理"]
* link:../get-started/prepare-cluster-admin.html["AFX システムの管理を準備する"]

