---
sidebar: sidebar 
permalink: faq-ontap-afx.html 
keywords: afx, afx system, faq, frequently asked questions 
summary: この FAQ リストには、AFX ストレージ システムに関して顧客が一般的に抱く質問に対する回答が記載されています。これには、AFX をより詳細に調査したり、高度な管理タスクを実行したりするときに役立つ概念と用語が含まれています。 
---
= AFX ストレージ システムに関する FAQ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
この FAQ リストには、AFX ストレージ システムに関してユーザーが抱く可能性のある質問に対する回答が記載されています。これには、AFX をより詳細に調査したり、高度な管理タスクを実行したりするときに役立つ概念と用語が含まれています。



== 全般

.ONTAPパーソナリティとは何ですか?
ONTAP は、包括的な機能セットと幅広いストレージ要件への適応性で知られる、堅牢で多用途なストレージ プラットフォームです。この柔軟性により、多様なワークロードを抱える組織にとって最適な選択肢となりますが、お客様によっては、特定の環境のニーズに合わせて最適化された、よりカスタマイズされたストレージ ソリューションからメリットを得られる場合もあります。

これらの特殊なニーズに対応するために、一部のNetAppストレージ システムでは、それぞれ独自の顧客要件をサポートするように設計された機能セットを含む、異なるONTAPパーソナリティを提供しています。  ONTAPパーソナリティは通常、ハードウェアとソフトウェアの機能を組み合わせたもので、対象となるユースケースに最適化されたエクスペリエンスを提供する目的で構築されています。  NetApp は、次の 3 つのONTAPパーソナリティを提供します。

* *Unified ONTAP* - Unified ONTAPパーソナリティは、NAS、SAN、S3 プロトコルをサポートする幅広いデータ管理機能を提供し、最大限の柔軟性を実現します。これはNetApp の主力製品であり、 AFFおよびFASシステムのほか、 ONTAP SelectやCloud Volumes ONTAPなどの仮想化展開でも利用できます。
* *AFX* - AFX ONTAPパーソナリティは、AI/ML アプリケーションを含む高性能 NAS および S3 ワークロードの厳しい要件を満たすように設計された分散型ソリューションを提供します。AFX システムは、スケーラブルで高スループットのファイルおよびオブジェクト ストレージを必要とする顧客向けに特殊な機能を提供します。
* * ASA r2* - ASA r2 ONTAPパーソナリティは、SAN のみの環境向けに特別に設計された分散型ソリューションを提供します。 https://docs.netapp.com/us-en/asa-r2/["ASA r2 システム"^]  ブロック ワークロードのストレージ エクスペリエンスを合理化し、SAN 顧客向けに最適化された簡素化された管理とパフォーマンスを提供します。


NetApp は、これらの明確なONTAP特性を提供することで、組織が運用要件とアプリケーション ワークロードに適合したストレージ ソリューションを選択できるようにします。

.NetAppストレージ システムのONTAPパーソナリティを変更できますか?
いいえ。ONTAPONTAPシステムのパーソナリティは不変であり、変更することはできません。たとえば、 FASまたはAFFストレージ システム (Unified ONTAPパーソナリティを実行) を AFX ストレージ システムに変換またはアップグレードすることはできません。

.さまざまなONTAPパーソナリティの System Manager インターフェイスはすべて非常によく似ています。特定のシステムのパーソナリティをどのように判断すればよいでしょうか?
System Manager の左側のナビゲーション ペインで *Cluster* を選択し、次に *Overview* を選択します。ページにパーソナリティが表示されます。代わりに、CLI でコマンド「system node show」を発行することもできます。  REST APIを使用してONTAPクラスタのパーソナリティを確認することもできます。link:./rest/first-call.html["最初のAFXシステムREST API呼び出し"]詳細については。

.AFX ストレージ システムはいつ利用可能になりましたか? AFX でサポートされている最も古いONTAPバージョンは何ですか?
AFX ストレージ システムは、2025 年 10 月のNetApp Insightカンファレンスで発表されました。AFX はONTAP 9.17.1 以降のリリースをサポートしています。詳細については、 NetApp の営業担当者にお問い合わせください。

.AFX ストレージ システムのコンテキストにおける「分散」とはどういう意味ですか?
「分解」という用語は、文脈に応じて、AFX では関連性のある 2 つの異なる意味を持つことがあります。

まず重要な概念は、コントローラー ノードのコンピューティング機能をストレージ シェルフから分離することです。 AFX では、Unified ONTAPパーソナリティを実行するFASおよびAFFシステムの場合のように、クラスターのコンピューティング コンポーネントとストレージ コンポーネントが密接に結合されなくなりました。代わりに、クラスター スイッチを介して接続されます。各 AFX ノード コントローラーは、クラスター ストレージ プール全体の完全なビューを持ちます。

分散ストレージに関連する 2 番目の概念は、集約と RAID 管理が管理可能なエンティティとして削除されることです。 AFX 内のストレージ抽象化レイヤーは、物理ディスクや RAID グループなどのストレージの低レベルの側面を自動的に構成および管理します。これにより、AFX 管理者はボリュームとバケットに基づいた高レベルのストレージ構成に集中できるようになります。



== 相互運用性

.同じONTAPクラスタ内で AFX システム ノードとAFF、 ASA、またはFASシステム ノードを混在させることはできますか?
いいえ。同じクラスタ内で異なるONTAPパーソナリティを実行するシステム ノードを混在させることはできません。たとえば、同じクラスタ内で AFX ノード (AFX ONTAPパーソナリティを実行) とAFFまたはFASノード (Unified ONTAPパーソナリティを実行) を混在させることはできません。

.FlexCache をAFX システム クラスターで使用できますか?
○AFX ストレージ システムは、Unified ONTAPパーソナリティを実行するAFFまたはFASシステムとの間のFlexCache をサポートします。唯一の制限は、ライトバック モードのFlexCache がAFX ではサポートされないことです。

.AFFまたはFASシステム (Unified ONTAPパーソナリティを実行) をSnapMirrorまたはFlexCacheの AFX システムと併用する場合、必要なONTAPのバージョンは何ですか?
AFX のSnapMirrorバージョン ルールは、Unified ONTAPと同じです。つまり、Unified ONTAPからレプリケートするには、ソース システムがサポートされているバージョン範囲内にある必要があります。  AFX からレプリケートするには、Unified ONTAPシステムがONTAP 9.16.1 以降 (Advanced Capacity Balancing 機能がサポートされている最も古いリリース) である必要があります。  FlexCacheの場合、ソースシステムと宛先システムに同じルールが適用されます。 https://www.netapp.com/pdf.html?item=/media/7336-tr4743.pdf["TR-4743"^] 。

FlexGroupボリュームのサポートにはいくつかの違いがあります。  AFX 上のFlexGroupボリュームは、Writeback モードを使用するFlexCacheボリュームの元のボリュームになることはできません。

.AFX クラスターに対して ONTAPI (ZAPI) API 呼び出しを行うことはできますか?
いいえ。AFX ではONTAP REST API のみがサポートされています。  ZAPI を使用する自動化コードは、AFX で使用するために REST API に変換する必要があります。



== 高度な概念

.AFX ストレージ システムでサポートされているデータ プロトコルは何ですか?
AFX でサポートされているデータ プロトコルは次のとおりです。

* NFSv3、NFSv4.0、NFSv4.1、NFSv4.2
* SMB2.x、SMB3.x
* S3
* NDMP


.AFX ではデータ プロトコルの動作が異なりますか?
いいえ。AFX のデータ プロトコルは、 AFFおよびFASシステムと同じように動作します。

.AFX では Advanced Disk Partitioning (ADP) が使用されていますか?
いいえ。ADP は AFX では使用されません。  AFX にはルート アグリゲートが存在しないため、ディスク領域効率を最大化するために ADP 機能は必要ありません。

.AFX ストレージ システムのバックエンド クラスター ネットワークでは、任意のタイプのスイッチを使用できますか?
いいえ。クラスター ネットワークでは、AFX ストレージ プラットフォーム用に特別に承認され、提供されているスイッチのみがサポートされます。また、これらのバックエンド スイッチは AFX クラスター操作専用です。クライアント アクセス操作 (NFS、SMB、S3 を使用) は、フロントエンド クライアント データ ネットワーク経由でのみ実行する必要があります。

.クラスター スイッチはどのように構成されていますか?
クラスタ ネットワーク スイッチは、 NetAppが提供する構成ファイルを使用して構成されます。構成ファイルへの変更はサポートされていません。

.AFX クラスター内のストレージはどのように構成されていますか?
AFX クラスターに接続されているすべてのディスクとストレージ シェルフは、ストレージ可用性ゾーン (SAZ) の一部です。各 AFX クラスターは 1 つの SAZ のみをサポートし、AFX クラスター間で共有することはできません ( SnapMirrorレプリケーションとFlexCache操作を除く)。

各ノードは SAZ 内のすべてのストレージを可視化できます。ストレージ シェルフがクラスターに追加されると、 ONTAPによってディスクが自動的に追加されます。

.AFX クラスターではデータはどのように割り当てられますか?
データが割り当てられると、SAZ 内の任意のディスクに配置できます。一度データを配置したら、移動する必要はありません。ボリュームは基礎となるデータに基づいて作成され、特定のノードに割り当てられます。ボリュームは、通常はバランス調整プロセスの一環として AFX によって移動できます。これは、どのノードのNVRAMがディスクへの書き込み操作をコミットするかに影響します。ボリュームを移動すると、ボリュームを所有するノードが変わりますが、データ自体はそのまま残ります。

.AFX は SAZ 全体のボリュームをどのように管理しますか?
AFX には、システムとユーザー オブジェクトの不均衡に対応する Automated Topology Management (ATM) と呼ばれる機能が含まれています。 ATM の主な目的は、AFX クラスター全体のボリュームのバランスを取ることです。不均衡が検出されると、アクティブ ノード全体にデータを均等に分散するための内部ジョブがトリガーされます。データは、オブジェクト メタデータのコピーと更新のみを必要とする ZCVM を使用して再割り当てされます。

.AFX クラスター内のノードにボリュームはどのように配置されますか?
NetApp AFX は、クラスター内のすべてのノード間でボリュームの配置を自動的に調整します。 ONTAP 9.18.1 以降では、ボリュームを配置または移動するときにノードのパフォーマンスを考慮するように配置アルゴリズムが強化されました。これにより、AFX クラスター内のノード間のパフォーマンスバランスが改善され、単一のノードが過負荷になる可能性が大幅に低くなります。以前の AFX リリースでは、クラスター内のボリュームの合計数に基づいて配置が決定されていました。アクティビティに関係なく、すべてのノードに同じ数のボリュームが割り当てられます。

.AFX では、ボリューム移動操作はAFFまたはFASシステムと比べてどのように異なりますか?
Unified ONTAPパーソナリティを実行するAFFおよびFASシステムでは、クラスタ内の 1 つのノードまたはアグリゲートから別のノードまたはアグリゲートにボリュームを無停止で再配置できます。これは、 SnapMirrorテクノロジーを使用したバックグラウンド コピー操作を使用して実行されます。ターゲットの宛先に新しい宛先ボリュームが作成されます。ボリュームのサイズとクラスター リソースの使用率に応じて、ボリューム移動操作が完了するまでにかかる時間は異なります。

AFX では集計はありません。すべてのストレージは、クラスター内のすべてのノードからアクセスできる単一のストレージ可用性ゾーン (SAZ) 内に含まれます。その結果、ボリュームの移動では実際にデータをコピーする必要がなくなります。代わりに、すべてのボリュームの移動は、ノード間のポインタの更新によって実行されます。これはゼロ コピー ボリューム移動 (ZCVM) と呼ばれ、実際にデータがコピーまたは移動されないため瞬時に実行されます。これは基本的に、 SnapMirrorコピーなしの Unified ONTAPで使用されるボリューム移動プロセスと同じです。

最初の 9.17.1 AFX リリースでは、ボリュームは、ストレージ フェイルオーバー回復シナリオと、クラスターに対してノードが追加または削除された場合にのみ移動します。これらの移動はONTAPを通じてのみ制御されます。
