---
sidebar: sidebar 
permalink: protect-data/prepare-protect-data.html 
keywords: afx, afx system, prepare, prepare protect, prepare protect data 
summary: AFX データを保護する前に、いくつかの重要な概念とストレージの現在の状態を理解しておく必要があります。 
---
= AFXストレージシステムのデータを保護する準備をする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFX データを保護する前に、いくつかの重要な概念と機能について理解しておく必要があります。


TIP: AFFおよびFASシステムで利用可能な概念や管理手順の多くはAFXストレージシステムと同じであるため、Unified ONTAPのドキュメントで https://docs.netapp.com/us-en/ontap/data-protection-disaster-recovery/index.html["データ保護とディザスタ リカバリ"^]役に立つかもしれません。



== 用語とオプション

AFX データ保護に関連して、知っておくべき用語がいくつかあります。

Snapshot:: スナップショットは、ボリュームの読み取り専用の特定時点のイメージです。これは、ONTAP のレプリケーションおよびデータ保護サービスの基盤となるテクノロジーです。
一貫性グループ:: 整合性グループは、1つの単位として管理されるボリュームの集まりです。整合性グループを作成すると、アプリケーション ワークロードのストレージ管理とデータ保護を簡素化できます。たとえば、個々のボリュームの代わりに整合性グループを使用することで、1 回の操作で複数のボリュームのスナップショットを作成できます。
階層的整合性グループ:: 階層的整合性グループはONTAP 9.16.1 で導入され、AFX で利用できます。階層構造では、1 つ以上の整合性グループを親の下の子として構成できます。これらの階層グループを使用すると、子の整合性グループに個別のスナップショット ポリシーを適用し、親を複製することで、すべての子のスナップショットを単一のユニットとしてリモート クラスターに複製できます。
SnapLock:: SnapLockは、ファイルを一度書き込み、何度も読み取り可能な (WORM) 状態に移行して保護できるONTAP の機能です。これにより、指定された保持期間中は変更や削除が防止されます。作成されたSnapLockボリュームは、保持期間に基づいて作成後に非SnapLockボリュームから変換することはできません。




== AFXデータ保護の制限

AFX ストレージ システムによって適用されるONTAPデータ保護の制限と制約事項を認識しておく必要があります。

.SnapMirror同期（SM-S）
SM-S を使用する場合、スケール制限があります。単一の AFX システム クラスター全体で最大 400 のリレーションシップを設定できます。



== 関連情報

* link:../administer/additional-ontap-svm.html["追加のAFX SVM管理"]
* link:../get-started/prepare-cluster-admin.html["AFXシステムを管理する準備をする"]

