---
sidebar: sidebar 
permalink: install-afx-2k/install-network-reqs.html 
keywords: shared storage cluster switch 
summary: ONTAP 9.9.1 以降では、 Cisco Nexus 9364d-gx2a スイッチを使用して、ストレージとクラスタ機能を共有スイッチ シナリオに組み合わせることができます。 
---
= AFX 2Kストレージシステムのネットワーク要件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
AFX 2Kストレージシステムに接続する各ネットワークについて、必要な情報を記録してください。



== ネットワーク情報を収集する

AFX 2Kストレージシステムのインストールを開始する前に、必要なネットワーク情報を収集してください。

* 各ストレージ システム コントローラおよび該当するすべてのスイッチのホスト名と IP アドレス。
+
ほとんどのストレージ システム コントローラは、イーサネット サービス ポート (レンチ アイコン) に接続して e0M インターフェイスを介して管理されます。

+
参照 https://hwu.netapp.com["Hardware Universe"^]最新情報についてはこちらをご覧ください。

* クラスタ管理IPアドレス
+
クラスター管理 IP アドレスは、クラスター管理者が管理ストレージ VM にアクセスしてクラスターを管理するために使用するクラスター管理インターフェイスの一意の IP アドレスです。このIPアドレスは、組織内でIPアドレスの割り当てを担当している管理者から取得できます。

* ネットワーク サブネット マスク
+
クラスタのセットアップ中に、 ONTAP は構成に適したネットワーク インターフェイスのセットを推奨します。必要に応じて推奨事項を調整できます。

* ネットワーク ゲートウェイのIPアドレス
* ノード管理 IP アドレス (ノードごとに 1 つ)
* DNSドメイン名
* DNSネームサーバーのIPアドレス
* NTPサーバーのIPアドレス
* データサブネットマスク
* 管理ネットワーク トラフィック用の IP サブネット。




== Ciscoスイッチのネットワーク要件

Cisco Nexus 9808、Cisco Nexus 9332D-GX2、および9364D-GX2Aスイッチの設置および保守については、ケーブル配線とネットワーク要件を必ず確認してください。



=== ネットワーク要件

すべてのスイッチ構成には次のネットワーク情報が必要です。

* 管理ネットワークトラフィック用の IP サブネット
* 各ストレージ システム コントローラおよび該当するすべてのスイッチのホスト名と IP アドレス
* 参照 https://hwu.netapp.com["Hardware Universe"^]最新情報についてはこちらをご覧ください。




=== ケーブル要件

* スイッチに適した数と種類のケーブルおよびケーブル コネクタがあります。参照 https://hwu.netapp.com["Hardware Universe"^]。
* 最初に設定するスイッチのタイプに応じて、付属のコンソール ケーブルを使用してスイッチのコンソール ポートに接続する必要があります。


.次の手順
ネットワーク要件を確認した後、link:cable-hardware.html["AFX 2Kストレージシステムのコントローラーとストレージシェルフをケーブルで接続します。"]。
