---
sidebar: sidebar 
permalink: administer/migrate-svm.html 
keywords: afx, afx system, svm, migrate svm 
summary: データ SVM を 1 つのONTAPクラスタから別の ONTAP クラスタに移行できます。  AFX を使用した SVM の移行は、Unified ONTAPの場合と同じように動作しますが、相互運用性に関する考慮事項がいくつかあります。  SVM 移行の実行の詳細については、Unified ONTAP のドキュメントを参照してください。 
---
= AFXストレージシステムSVMの移行
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データ SVM を 1 つのONTAPクラスタから別の ONTAP クラスタに移行できます。  AFX を使用した SVM の移行は、Unified ONTAPの場合と同じように動作しますが、相互運用性に関する考慮事項がいくつかあります。  SVM 移行の実行の詳細については、提供されている Unified ONTAP のドキュメントを参照してください。



== 相互運用性の考慮事項

SVM の移行を計画して実行する前に、機能や制限などの相互運用性に関する考慮事項を認識しておく必要があります。



=== ユースケース

クラスタ管理者は、SVM をソース クラスタから宛先クラスタに再配置できます。これは、容量管理と負荷分散の一環として、または機器のアップグレードやデータ センターの統合を可能にするために実行できます。

また、AFX ストレージ システムは Unified ONTAPからのインプレース アップグレードをサポートしていないため、SVM の移行は重要なユース ケースとなります。アプリケーション ワークロードを、Unified ONTAP9 クラスターから AFX クラスターに中断なく移動できます。さらに、SVM は、AFX クラスターから Unified ONTAPクラスターへ、また AFX クラスター間での移行など、他の方法でも移行できます。



=== バージョンの相互運用性

次の表は、ソース クラスタと宛先クラスタのONTAPパーソナリティとリリースに基づいて許可される SVM 移行を示しています。

[cols="40,30,30"]
|===
| 送受信方向 | ソースバージョン | 宛先バージョン 


| AFXに統合 | 9.15.1 - 9.17.1 | 9.17.1 


| AFXからUnifiedへ | 9.17.1 | 9.17.1 


| AFXからAFXへ | 9.17.1 | 9.17.1 
|===


=== 事前確認

Unified ONTAPには、AFX でも実装されているいくつかの事前チェックが含まれています。さらに、AFX でサポートされていない機能にフラグを設定するための、次のようないくつかの新しい事前チェックが追加されました。

* FabricPool （複合アグリゲート上に存在するボリューム）
* シックプロビジョニングボリューム




=== ボリュームプロビジョニング

AFX ボリュームは、クラスターのストレージ可用性ゾーン (SAZ) 全体にわたって配置のバランスをとるためにプロビジョニングされます。

スペース保証:: AFX はシックプロビジョニングをサポートしていません。移行対象の SVM 内のいずれかのボリュームがシック プロビジョニングされている場合、事前チェックを使用して移行を失敗させます。
暗号化:: AFX システムはNetAppボリューム暗号化 (NVE) をサポートしますが、 NetAppアグリゲート暗号化 (NAE) はサポートしません。このため、Unified ONTAPクラスタのすべての NAE ボリュームは、AFX に移行されると NVE ボリュームに変換されます。次の表は互換性と変換をまとめたものです。


[cols="50,50"]
|===
| ソース ボリューム | デスティネーション ボリューム 


| プレーンテキスト | プレーンテキスト 


| NVE | NVE 


| ナエ | NVE 
|===


== 関連情報

* https://docs.netapp.com/us-en/ontap/svm-migrate/index.html["ONTAP SVMデータモビリティ"^]
* link:../faq-ontap-afx.html["AFX ストレージ システムに関する FAQ"]

