---
sidebar: sidebar 
permalink: get-started/compare-unified-ontap.html 
keywords: afx, afx system, compare afx, compare unified ontap 
summary: 'NetApp AFX システムは、 AFFおよびFASストレージ上で実行されるONTAPパーソナリティ (Unified ONTAPと呼ばれる) とは異なる、カスタマイズされたONTAPパーソナリティを実行します。 AFX システムとFASシステムおよびAFFシステムとの類似点と相違点を認識しておく必要があります。これは貴重な視点を提供し、環境に AFX を展開するときに役立ちます。' 
---
= AFXストレージシステムをAFFおよびFASシステムと比較する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp AFX システムは、 AFFおよびFASストレージ上で実行されるONTAPパーソナリティ (Unified ONTAPと呼ばれる) とは異なる、カスタマイズされたONTAPパーソナリティを実行します。 AFX システムとFASシステムおよびAFFシステムとの類似点と相違点を認識しておく必要があります。これは貴重な視点を提供し、環境に AFX を展開するときに役立ちます。


TIP: AFX ドキュメントには、 ONTAPパーソナリティに関係なく同じように動作する機能の詳細については、Unified ONTAPドキュメント サイトのさまざまなトピックへのリンクが含まれています。追加コンテンツでは、AFX ストレージ システムの管理に役立つ詳細な情報が提供されます。



== 構成の違い

AFX 構成がAFFおよびFASシステムと異なる領域がいくつかあります。

高度な容量バランス調整:: 高度な容量バランス調整機能は、 `-gdd` CLI パラメータは、すべてのFlexGroupボリュームに対してデフォルトで有効になっています。




== サポートされていない、または制限されているUnified ONTAPの機能

NetApp AFX は、高パフォーマンス NAS およびオブジェクト ワークロード向けに最適化されています。このため、 AFFやFASなどの他の Unified ONTAPストレージ システムとは違いがあります。次の機能はNetApp AFX では利用できません。リストは主要な機能または機能領域別にまとめられています。  AFXのアップデートと変更点も確認する必要があります。link:../release-notes/whats-new-9171.html["新機能"]あなたのリリースに基づいて。



=== ブロックとSAN

* SAN管理とクライアントアクセス
* LUNとNVMe名前空間
* ボリュームのシックプロビジョニング




=== 集約と物理的なストレージ

* MetroCluster
* 物理ノード所有アグリゲート
* RAIDの管理
* NetApp Aggregate Encryption（NAE）
* アグリゲートレベルの重複排除
* SyncMirror （集約ミラーリング）
* FabricPool の階層化




=== データレプリケーション（SnapMirror）


NOTE: すべてのデータレプリケーションは、Unified ONTAPとAFXの間で双方向にサポートされますが、バージョン制限は同じです。 https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html["SnapMirror関係に対応したONTAPバージョン"^] (いくつかの小さな例外を除く)。

* LUN または NVMe 名前空間を含むAFFまたはFASシステムからのボリュームのレプリケーションは実行できません。
* FlexGroupボリュームは、AFXからUnified ONTAPバージョン9.16.1以降にのみ複製できます（高度な容量バランシングが必要なため）




=== 管理性

* ONTAPI API (ZAPI)
* サポートされていない機能（ MetroClusterなど）用のREST API
* パフォーマンス統計用のREST APIの初期制限
* AIQ Unified Managerのサポート
* Grafana Harvest バージョン 25.08.1 以降
* NetApp Tridentバージョン 25.10 以降




== コマンドラインインターフェースの変更

AFX で使用できるONTAP CLI は、通常、 AFFおよびFASシステムで使用できる CLI と同じです。ただし、次のような違いがいくつかあります。

* 関連する新しい AFX コマンド:
+
** ストレージ可用性ゾーンの容量を表示する
** ブート メディア


* SAN関連のコマンドはありません
* 集計管理コマンドは不要になりました
* 集計表示では、ストレージ可用性ゾーン (SAZ) 全体が表示されるようになりました。




== 関連情報

* link:../get-started/system-design.html["AFXシステムの特徴"]
* link:../get-started/software-architecture.html["AFXアーキテクチャの詳細"]
* link:../faq-ontap-afx.html["AFX ストレージ システムに関する FAQ"]
* link:../administer/additional-ontap-cluster.html["追加のAFXクラスター管理"]
* link:../administer/additional-ontap-svm.html["追加のAFX SVM管理"]

