---
sidebar: sidebar 
permalink: get-started/ontap-afx-storage.html 
keywords: afx, afx system, learn, workloads, hardware, afx 1k, nx224, cisco 
summary: NetApp AFX ストレージ システムは、 ONTAPストレージ モデルを分散型の高性能 NAS ソリューションに進化させた次世代ストレージ アーキテクチャに基づいています。  AFX は、非常に高いパフォーマンスを提供する高度なテクノロジーと処理手法により、ファイルとオブジェクトの両方のワークロードをサポートします。 
---
= AFXストレージシステムについて学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp AFX ストレージ システムは、 ONTAPストレージ モデルを分散型の高性能 NAS ソリューションに進化させた次世代ストレージ アーキテクチャに基づいています。  AFX は、非常に高いパフォーマンスを提供する高度なテクノロジーと処理手法により、ファイルとオブジェクトの両方のワークロードをサポートします。



== 一般的なアプリケーションのワークロード

AFX ストレージは、AI/ML 環境やその他の関連するデータ中心のアプリケーションに特有の要求を満たします。  AFX ストレージ システムは、次のようなさまざまなワークロードを管理する組織に最適です。

* 継続的な高帯域幅と大規模なデータセットへのアクセスが必要なディープラーニングに関連するトレーニングと反復的なモデルの改良。
* テキスト、画像、ビデオなど、さまざまなデータ タイプを処理します。
* 厳密な応答時間ウィンドウが必要な低遅延のリアルタイム推論アプリケーション。
* データ エンジニアとデータ サイエンティストによるセルフサービス データ管理のメリットを享受できるデータ サイエンスと機械学習のパイプライン。
* RDMA トランスポートを備えたマルチ GPU システムなど、高い同時実行性と並列 I/O を必要とするワークロード。




== ハードウェアインフラストラクチャ

NetApp AFX ストレージ システムは、高性能 NAS 顧客のニーズに特化した簡素化されたエクスペリエンスを実現する、統合されたハードウェアおよびソフトウェア ソリューションを提供します。

AFX クラスターでは次のハードウェア コンポーネントが使用されます。

* AFX 1Kコントローラー
* NX224 棚
* Cisco Nexus 9332D-GX2B または Nexus 9364D-GX2A スイッチ

