---
sidebar: sidebar 
permalink: get-started/ontap-afx-storage.html 
keywords: afx, afx system, learn, workloads, hardware, afx 1k, nx224, cisco 
summary: NetApp AFX ストレージ システムは、 ONTAPストレージ モデルを分散型の高性能 NAS ソリューションに進化させた次世代ストレージ アーキテクチャに基づいています。  AFX は、非常に高いパフォーマンスを提供する高度なテクノロジーと処理手法により、ファイルとオブジェクトの両方のワークロードをサポートします。 
---
= AFXストレージシステムについて学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp AFX ストレージ システムは、 ONTAPストレージ モデルを分散型の高性能 NAS ソリューションに進化させた次世代ストレージ アーキテクチャに基づいています。  AFX は、非常に高いパフォーマンスを提供する高度なテクノロジーと処理手法により、ファイルとオブジェクトの両方のワークロードをサポートします。



== 一般的なアプリケーションのワークロード

NetApp AFX ストレージ システムは、高いパフォーマンスと独立したスケールを必要とする NAS および S3 オブジェクト ワークロードの固有の要求を満たします。これらのアプリケーションは、高い同時実行性と並列 I/O に基づいて構築された高度な設計の恩恵を受けます。  AFX は、次のようなさまざまな種類のアプリケーション ワークロードを展開および管理する組織に最適です。

* 継続的な高帯域幅と大規模なデータセットへのアクセスが必要なディープラーニングに関連するトレーニングと反復的なモデルの改良。
* テキスト、画像、ビデオなど、さまざまなデータ タイプを処理します。
* 厳密な応答時間ウィンドウが必要な低遅延のリアルタイム推論アプリケーション。
* データ エンジニアとデータ サイエンティストによるセルフサービス データ管理のメリットを享受できるデータ サイエンスと機械学習のパイプライン。




== システム設計の特徴

AFX システムには、高性能 NAS プラットフォームとして動作できるようにするいくつかの設計特性があります。

ストレージとコンピューティング機能を分離する:: 他のNetApp ONTAPストレージ システムとは異なり、AFX クラスターのコンピューティング要素とストレージ要素は分離されており、スイッチ ネットワークを介して結合されます。ディスクの所有権が特定のノードに結び付けられなくなり、いくつかの利点がもたらされます。たとえば、AFX クラスターのコンピューティング コンポーネントとストレージ コンポーネントは個別に拡張できます。
自動ストレージ管理:: 物理アグリゲートは、AFX ストレージ管理者には利用できなくなります。代わりに、AFX は、新しいストレージ シェルフがクラスターに追加されると、ノードの仮想容量割り当てと RAID グループ構成を自動的に管理します。この設計により管理が簡素化され、専門家以外の人でもデータを管理できるようになります。
クラスター用の単一のストレージプール:: ストレージ ノードとシェルフはNetApp AFX によって分離されているため、クラスターのすべてのストレージ容量は、ストレージ可用性ゾーン (SAZ) と呼ばれる単一のプールに集められます。 SAZ 内のディスクとシェルフは、AFX クラスター内のすべてのストレージ ノードで読み取りおよび書き込み操作に使用できます。さらに、障害が発生した場合、すべてのクラスター ノードがディスクの再構築に参加できます。参照link:../faq-ontap-afx.html["AFX ストレージ システムに関する FAQ"]詳細についてはこちらをご覧ください。
ハイ パフォーマンス:: NetApp AFX は、超低レイテンシで高い持続帯域幅を提供するため、高パフォーマンスの NAS およびオブジェクト ワークロード向けに設計されています。 AFX は、独自のアーキテクチャにより、最新のハードウェアと、高いノード対ディスク比率を処理できるストレージ シェルフを使用します。ストレージ ノードを通常の 1:1 (ノード:シェルフ) 比率を超えて拡張すると、ディスクのパフォーマンス プロファイルが限界まで最大化されます。この設計により、最も重要なアプリケーションに効率性とストレージ密度がもたらされます。
独立性と大規模性:: 分離されたストレージ ノードとシェルフに基づいて、AFX クラスターはアプリケーションのニーズに応じて独立して中断なく拡張できます。ストレージ ノードを追加して CPU とスループットを向上させたり、シェルフを追加してストレージ容量とディスク パフォーマンスを向上させることができます。  NetApp AFX アーキテクチャは、クラスターの最大サイズに新たな可能性をもたらします。  ONTAPリリースに基づく AFX クラスターの最新の制限については、 NetApp Hardware Universeを参照してください。
ゼロコピーデータモビリティ:: NAS およびオブジェクト クライアントは、 ONTAPクラスターのボリュームにアクセスします。容量とパフォーマンスのバランスの目標を達成するために、ノード間でボリュームを中断せずに再配置できます。 Unified ONTAPでは、ボリュームの移動はSnapMirrorテクノロジーを使用して実行されるため、時間がかかり、一時的な容量が追加される可能性があります。しかし、AFX を使用すると、共有ストレージ可用性ゾーン (SAZ) 内でのデータ コピー操作は不要になります。代わりに、ボリューム メタデータのみが移動されるため、パフォーマンスが大幅に向上します。参照link:../faq-ontap-afx.html["AFX ストレージ システムに関する FAQ"]詳細についてはこちらをご覧ください。
強化されたHA機能:: NetApp AFX は、高可用性 (HA) 構成と処理のためのさまざまな機能強化を提供します。 AFX により、HA パートナー ノードを直接接続する必要がなくなり、代わりに HA ペアが内部クラスター ネットワークを介して通信できるようになります。この設計により、管理者はフォールト トレランスを強化するために、データセンター内の別々のラックまたは列に HA ペアを展開するオプションを利用できるようになります。さらに、AFX ゼロ コピー モビリティは HA フェイルオーバー シナリオにも拡張されます。ノードに障害が発生すると、そのボリュームは HA パートナーにフェイルオーバーされ、残りの書き込みがディスクにコミットされます。次に、 ONTAP はクラスタ内のすべての残存ノード間でボリュームを均等に分散します。つまり、データ配置の初期設計でストレージ フェイルオーバーのパフォーマンスを考慮する必要がなくなります。




== ハードウェアインフラストラクチャ

NetApp AFX ストレージ システムは、高性能 NAS 顧客のニーズに特化した簡素化されたエクスペリエンスを実現する、統合されたハードウェアおよびソフトウェア ソリューションを提供します。


TIP: 確認すべきはlink:../faq-ontap-afx.html["AFX ストレージ システムに関する FAQ"]ハードウェアの相互運用性とアップグレード オプションの詳細については、こちらをご覧ください。

AFX クラスターでは次のハードウェア コンポーネントが使用されます。

* AFX 1Kコントローラー
* NX224 棚
* Cisco Nexus 9332D-GX2B または Nexus 9364D-GX2A スイッチ




== 関連情報

* https://hwu.netapp.com/["NetApp Hardware Universe"^]
* https://www.netapp.com/afx/["NetApp AFX"^]

