---
sidebar: sidebar 
permalink: get-started/ontap-afx-storage.html 
keywords: afx, afx system, learn, workloads, hardware, afx 1k, nx224, cisco 
summary: NetApp AFX ストレージ システムは、 ONTAPストレージ モデルを分散型の高性能 NAS ソリューションに進化させた次世代ストレージ アーキテクチャに基づいています。  AFX は、非常に高いパフォーマンスを提供する高度なテクノロジーと処理手法により、ファイルとオブジェクトの両方のワークロードをサポートします。 
---
= AFXストレージシステムについて学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp AFX ストレージ システムは、 ONTAPストレージ モデルを分散型の高性能 NAS ソリューションに進化させた次世代ストレージ アーキテクチャに基づいています。  AFX は、非常に高いパフォーマンスを提供する高度なテクノロジーと処理手法により、ファイルとオブジェクトの両方のワークロードをサポートします。



== 一般的なアプリケーションのワークロード

NetApp AFX ストレージ システムは、AI/ML 環境やその他の関連するデータ中心のアプリケーションに特有の要求を満たします。AFX ストレージ システムは、次のようなさまざまなワークロードを管理する組織に最適です。

* 継続的な高帯域幅と大規模なデータセットへのアクセスが必要なディープラーニングに関連するトレーニングと反復的なモデルの改良。
* テキスト、画像、ビデオなど、さまざまなデータ タイプを処理します。
* 厳密な応答時間ウィンドウが必要な低遅延のリアルタイム推論アプリケーション。
* データ エンジニアとデータ サイエンティストによるセルフサービス データ管理のメリットを享受できるデータ サイエンスと機械学習のパイプライン。
* RDMA トランスポートを備えたマルチ GPU システムなど、高い同時実行性と並列 I/O を必要とするワークロード。




== システム設計の特徴

AFX システムには、高性能 NAS プラットフォームとして動作できるようにするいくつかの設計特性があります。

ストレージとコンピューティング機能を分離する:: AFFおよびFASストレージ システムとは異なり、クラスターの AFX ストレージ要素とコンピューティング要素は分離されています。  AFX コントローラーは、限られたローカル ディスクのセットにアクセスすることに制限されません。
アグリゲートとRAID管理の削除:: ストレージ管理者は、アグリゲートと RAID グループを管理する必要がなくなります。  AFX はこれらのタスクを処理するため、管理が簡素化され、専門家以外のユーザーでもデータを管理できるようになります。
クラスター用の単一のストレージプール:: AFX のコンピューティングとストレージを分離し、ストレージ管理を簡素化することで、単一のストレージ プールが実現します。このストレージ可用性ゾーン (SAZ) は、AFX クラスター内のすべてのコントローラー ノードで使用できます。見るlink:../faq-ontap-afx.html["AFX ストレージ システムに関する FAQ"]詳細についてはこちらをご覧ください。
ハイ パフォーマンス:: AFX は、特殊な AI/ML アプリケーションに必要な高パフォーマンスを実現するように構築されています。最新のハードウェアをより効率的に使用して、超低遅延で高く持続的な帯域幅を提供できます。
操作のシンプルさ:: 単一のストレージ プールと、自動ストレージ管理などの他の機能により、はるかにシンプルな管理および運用モデルが実現します。
拡張性:: クラスター内のコントローラー ノードとストレージ シェルフのセットは、アプリケーションのニーズに基づいて個別に拡張できます。コントローラまたはシェルフを追加する場合、管理要件と中断は限られます。
データモビリティの向上:: ボリュームは、実際にデータをコピーすることなく、クラスター コントローラー ノード間で中断なく移動できます。代わりにメタデータ ディレクトリとインデックス ポインターが更新されます。これにより、一般的な管理手順や障害シナリオの回復時のパフォーマンスが大幅に向上します。




== ハードウェアインフラストラクチャ

NetApp AFX ストレージ システムは、高性能 NAS 顧客のニーズに特化した簡素化されたエクスペリエンスを実現する、統合されたハードウェアおよびソフトウェア ソリューションを提供します。

AFX クラスターでは次のハードウェア コンポーネントが使用されます。

* AFX 1Kコントローラー
* NX224 棚
* Cisco Nexus 9332D-GX2B または Nexus 9364D-GX2A スイッチ




== 関連情報

* https://www.netapp.com/afx/["NetApp AFX"^]

