---
sidebar: sidebar 
permalink: get-started/system-design.html 
keywords: afx, afx system, characteristics, design 
summary: NetApp AFX ストレージ システムには、高性能 NAS プラットフォームとして動作できるようにするいくつかの特性があります。 
---
= AFXストレージシステムの特徴
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp AFX ストレージ システムには、高性能 NAS プラットフォームとして動作できるようにするいくつかの特性があります。

ストレージとコンピューティング機能を分離する:: AFFおよびFASストレージ システムとは異なり、クラスターの AFX ストレージ要素とコンピューティング要素は分離されています。  AFX コントローラーは、限られたローカル ディスクのセットにアクセスすることに制限されません。
アグリゲートとRAID管理の削除:: ストレージ管理者は、アグリゲートと RAID グループを管理する必要がなくなります。  AFX はこれらのタスクを処理するため、管理が簡素化され、専門家以外のユーザーでもデータを管理できるようになります。
クラスター用の単一のストレージプール:: AFX のコンピューティングとストレージを分離し、ストレージ管理を簡素化することで、単一のストレージ プールが実現します。このストレージ可用性ゾーン (SAZ) は、AFX クラスター内のすべてのコントローラー ノードで使用できます。見るlink:../faq-ontap-afx.html["AFX ストレージ システムに関する FAQ"]詳細についてはこちらをご覧ください。
ハイ パフォーマンス:: AFX は、特殊な AI/ML アプリケーションに必要な高パフォーマンスを実現するように構築されています。最新のハードウェアをより効率的に使用して、超低遅延で高く持続的な帯域幅を提供できます。
操作のシンプルさ:: 単一のストレージ プールと、自動ストレージ管理などの他の機能により、はるかにシンプルな管理および運用モデルが実現します。
拡張性:: クラスター内のコントローラー ノードとストレージ シェルフのセットは、アプリケーションのニーズに基づいて個別に拡張できます。コントローラまたはシェルフを追加する場合、管理要件と中断は限られます。
データモビリティの向上:: ボリュームは、実際にデータをコピーすることなく、クラスター コントローラー ノード間で中断なく移動できます。代わりにメタデータ ディレクトリとインデックス ポインターが更新されます。これにより、一般的な管理手順や障害シナリオの回復時のパフォーマンスが大幅に向上します。

