---
sidebar: sidebar 
permalink: release-notes/changes-to-limits-defaults.html 
keywords: release notes, changes, updates, defaults, limits, afx storage system, afx system, afx 
summary: AFXシステムに影響を与える制限事項とデフォルト値の変更点についてご確認ください。NetAppは、各ONTAPリリースにおける最も重要なデフォルト値と制限事項の変更をお客様にご理解いただけるよう努めています。 
---
= AFX システムに影響を与える ONTAP の制限とデフォルトの変更
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
AFXシステムに影響を与える制限事項とデフォルト値の変更点についてご確認ください。NetAppは、各ONTAPリリースにおける最も重要なデフォルト値と制限事項の変更をお客様にご理解いただけるよう努めています。


TIP: AFX クラスターの機能を判断するには、 NetApp Hardware Universeおよび Interoperability Matrix Tool で入手できる詳細情報を確認する必要があります。



[[changes-to-ontap-limits]]
== ONTAPの制限に対する変更

[cols="1,3,1"]
|===
| 機能 | 制限の変更点 | リリースで変更 


| クラスタあたりのノード数  a| 
AFXクラスターは最大32ノードまで拡張できます。これにより、ワークロードやアプリケーションの増大する需要に合わせて、AFXストレージシステムを拡張することが可能になります。32ノードのサポートは限定的な機能セットで利用可能です。詳細については、NetAppアカウントチームにお問い合わせください。
| ONTAP 9.19.1 


| FlexGroupあたりのボリューム数  a| 
FlexGroup の最大ボリューム数が、32ノードで512に増加しました。これにより、AFXストレージシステムは、より大規模なクラスターに対しても、その性能を最大限に発揮できるようになります。
| ONTAP 9.19.1 


| SnapMirror クラウドサポート  a| 
SnapMirror クラウドでサポートされる S3 バケットの最大数が 100 に増加しました。これにより、ワークロードやアプリケーション用にさらに多くの S3 バケットを作成できます。
| ONTAP 9.19.1 
|===


[[related-information]]
== 関連情報

* https://hwu.netapp.com/["NetApp Hardware Universe"^]
* https://imt.netapp.com/["NetApp Interoperability Matrix Tool"^]
* https://docs.netapp.com/us-en/interoperability-matrix-tool/["相互運用性マトリックスツールの概要"^]

