---
sidebar: sidebar 
permalink: release-notes/whats-new-9191.html 
keywords: 'afx, release notes, what"s new, 9.19.1' 
summary: AFXストレージシステムで利用可能なONTAP 9.19.1に含まれる新機能について説明します。 
---
= ONTAP 9.19.1 for AFX ストレージシステムの新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
AFXストレージシステムで利用可能なONTAP 9.19.1に含まれる新機能について説明します。


NOTE: AFXには、ONTAP 9.19.1で利用可能な新機能がいくつかあります。これらのうちいくつかはAFX固有のものですが、その他多くは共通の製品基盤から派生したものです。下記に説明するAFXの機能を確認することに加えて、以下も参照してください https://docs.netapp.com/us-en/ontap/release-notes/whats-new-9191.html["ONTAP 9.19.1の新機能"^]。



[[data-protection]]
== データ保護

[cols="2,4"]
|===
| 更新 | 説明 


| link:../administer/additional-ontap-svm.html["ONTAP SnapMirror アクティブ同期で NAS を保護する"]  a| 
SnapMirror active syncは、AFXクラスタ（4ノードのみ）上でNFSとSMBを使用してSVMレベルでNASワークロードをサポートし、プライマリクラスタ上では読み取り/書き込みアクセスのみをサポートします。



| link:../manage-data/create-configure-bucket.html["SnapMirrorクラウドサポートの制限がS3バケット100個に引き上げられました"]  a| 
SnapMirror クラウドでサポートされる S3 バケットの数が 100 に増加しました。

|===


[[networking]]
== ネットワーク

[cols="2,4"]
|===
| 更新 | 説明 


| link:../administer/additional-ontap-cluster.html#performance["TCPのパフォーマンス向上"]  a| 
ONTAP 9.19.1以降、ONTAPはPRRとRACKという2つの損失回復機能をONTAP TCPスタックに統合することで、損失が多く遅延の大きいWANリンク上のTCPデータ転送パフォーマンスを向上させます。

|===


[[performance]]
== Performance

[cols="2,4"]
|===
| 更新 | 説明 


| Cross File Sequential Read（CFSR）  a| 
クロスファイルシーケンシャルリードは、特定のメディアおよびエンターテイメントワークロードにおいて、読み取りパフォーマンスを大幅に向上させることができます。この機能は、連続するビデオフレームをインテリジェントにプリフェッチすることで、ビデオ編集アプリケーションのスループットを劇的に向上させ、レイテンシを低減します。詳細については、link:../administer/additional-ontap-svm.html["AFX ストレージ システム SVM の追加管理"]を参照してください。



| グローバル重複排除  a| 
グローバル重複排除により、ONTAPの重複排除による容量削減効果がストレージの可用性ゾーン（SAZ）全体に拡張されます。SAZ内のすべてのボリュームにわたる重複データブロックを排除することで、ストレージ効率を大幅に向上させ、総所有コストを削減できます。この機能はAFXシステムではデフォルトで有効になっており、管理者による設定を必要とせずに透過的に動作します。詳細については、link:../administer/additional-ontap-svm.html["AFX ストレージ システム SVM の追加管理"]を参照してください。



| 動的ストレージ効率  a| 
Dynamic Storage Efficiency は、高いパフォーマンスと最大のスループットを必要とする大規模なワークロード向けに、ストレージ効率化操作（圧縮、重複排除、コンパクション）をインテリジェントに最適化します。大量の書き込み状況を自動的に検知し、ピーク時の負荷によるパフォーマンス低下を防ぐため、インラインおよびバックグラウンドのストレージ効率化プロセスを一時的に停止します。スループットが規定のしきい値を下回ると、ストレージ効率化操作が再開され、手動による介入なしに節約効果が回復されます。この機能は AFX ストレージシステムで利用可能で、デフォルトで有効になっており、設定は不要です。

|===


[[rest-api]]
== REST API

[cols="2,4"]
|===
| 更新 | 説明 


| Kubernetesストレージオーケストレーションにおけるバランスのとれた配置機能の強化  a| 
ONTAP 9.19.1では、 `/storage/volumes` REST APIエンドポイントで現在利用可能な6つのパラメータが `/applications/containers`エンドポイントに追加されます。この機能強化により、Kubernetesストレージオーケストレーション用のNetApp Tridentを使用しているお客様は、ONTAPのネイティブなバランス配置機能を使用してボリュームを作成できます。

|===


[[s3-object-storage]]
== S3オブジェクト ストレージ

[cols="30%,70%"]
|===
| 更新 | 説明 


 a| 
xref:../manage-data/manage-buckets.html[AFXストレージシステムバケットを管理する]
 a| 
条件を使用することで、オブジェクトのアップロードに対して条件付き書き込みを、オブジェクトの削除に対して条件付き削除を強制できます。条件付き書き込みと削除は、オブジェクトの上書きや意図しない削除を防ぐ手段を提供します。



 a| 
xref:../manage-data/manage-buckets.html[AFXストレージシステムバケットを管理する]
 a| 
元のアクセスキーの有効期限が切れた場合でも、S3 リソースへのユーザーアクセスを維持するには、ONTAPクラスター管理者は、S3ユーザーごとに2つ目のアクセスキーを生成できます。

|===


[[security]]
== セキュリティ

[cols="2,4"]
|===
| 更新 | 説明 


| https://docs.netapp.com/us-en/ontap/anti-ransomware/use-cases-restrictions-concept.html#snapmirroreligible["ARP/AIによるSnapMirrorプライマリボリュームのサポート"^]  a| 
ARP/AIは、AFXシステムとのSnapMirror同期関係にある対象のプライマリボリュームをサポートしています。ARP/AIは、アクティブな読み書き可能なプライマリボリューム上で動作し、プライマリ専用のARPスナップショットを作成し、機械学習ベースのランサムウェア検出を提供します。



| link:../administer/additional-ontap-cluster.html["TLS ハードウェアオフロードのサポート"]  a| 
サポートされているイーサネットカードに、クラスタ全体のトランスポート層セキュリティ（TLS）の暗号化と復号化をオフロードできます。これにより CPU 負荷が軽減され、TLS を使用するシステムのパフォーマンスが向上します。



| link:../administer/additional-ontap-svm.html["NFS over TLS v3"]  a| 
ONTAP 9.19.1 以降、ONTAP は NFS 対応 SVM 上で転送中の NFS トラフィックを暗号化するために、TLS 1.3 を使用した NFS over TLS のオンプレミスサポートを追加します。今回のリリースでは、LIF ごとのオプションの相互 TLS ホスト認証と、一致するクライアントからの非 TLS TCP アクセスを拒否するためのエクスポートポリシー制御もサポートされています。

|===


[[storage-resource-management]]
== ストレージ リソースの管理

[cols="2,4"]
|===
| 更新 | 説明 


| link:../administer/monitor-cluster-performance.html["System Manager によるストレージの可用性ゾーン容量の詳細のサポート。"]  a| 
System Managerでは、スペースしきい値、Snapshotによって消費されるスペース、データ削減など、ストレージの可用性ゾーン容量の詳細を表示できます。また、ONTAPで警告および重大アラートを生成する割合にスペース使用率のしきい値を設定することもできます。



| link:../administer/additional-ontap-cluster.html["自動QoSスループット上限の増加を制御するデフォルト設定の変更のサポート"]  a| 
QoSポリシーグループが、短期的なパフォーマンス向上ニーズに応じてQoSスループットの上限を自動的に引き上げる方法を制御するデフォルト設定を変更できます。これらの設定は、ONTAP 9.18.1以前では変更できません。

|===


[[upgrade]]
== Upgrade

[cols="2,4"]
|===
| 更新 | 説明 


| link:../administer/upgrade-ontap.html["自動アップグレード前チェックのレポート機能の強化"]  a| 
自動アップグレード前チェックを実行する際、エラーと警告は別々に表示されるため、アップグレード前に解決する必要のある問題を簡単に特定できます。

|===
.関連情報
* https://docs.netapp.com/us-en/ontap/release-notes/index.html["ONTAP 9リリース ハイライト"^]

