---
sidebar: sidebar 
permalink: release-notes/whats-new-9171.html 
keywords: 'afx, release notes, what"s new, 9.17.1' 
summary: AFX ストレージ システムで利用できるONTAP 9.17.1 に含まれる新機能について説明します。 
---
= AFXストレージシステム向けONTAP 9.17.1の新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
AFX ストレージ システムで利用できるONTAP 9.17.1 に含まれる新機能について説明します。


NOTE: AFX には、ONTAP 9.17.1 で利用可能な新機能がいくつかあります。これらのうちいくつかは AFX 固有のものですが、その他多くは共通の製品基盤から派生したものです。以下に説明する AFX の機能を確認することに加えて、 https://docs.netapp.com/us-en/ontap/release-notes/whats-new-9171.html["ONTAP 9.17.1の新機能"^]も参照してください。



[[platforms]]
== プラットフォーム

[cols="2,4"]
|===
| 更新 | 説明 


| プラットフォーム  a| 
次のNetApp AFX ストレージ システム コンポーネントは、関連するサポート テクノロジとともに利用できます。このプラットフォームを組み合わせることで、高性能 NAS および S3 の顧客のニーズに特化した、簡素化されたエクスペリエンスを生み出す統合ハードウェアおよびソフトウェア ソリューションが実現します。

* AFX 1Kコントローラー
* NX224 棚
* Cisco Nexus 9332D-GX2B および Nexus 9364D-GX2A スイッチ


|===


[[storage-resource-management-enhancements]]
== ストレージ リソース管理の機能拡張

[cols="30%,70%"]
|===
| 更新 | 説明 


 a| 
xref:../manage-data/monitor-debug-storage.html[AFX ストレージ システムの監視とトラブルシューティング]
 a| 
NASプロトコル用に割り当てられたONTAPクラスタ上の新規作成されたSVM上に作成されたボリュームでは、ファイルシステム分析（FSA）がデフォルトで有効になっています。FSAはボリュームの作成と同時に自動的に有効化され、追加設定なしですぐに分析機能を利用できます。

|===


[[related-information]]
== 関連情報

* https://docs.netapp.com/us-en/ontap/release-notes/index.html["ONTAP 9リリース ハイライト"^]

