---
sidebar: sidebar 
permalink: release-notes/whats-new-9181.html 
keywords: 'afx, release notes, what"s new, 9.18.1' 
summary: AFX ストレージ システムで利用できるONTAP 9.18.1 に含まれる新機能について説明します。 
---
= AFXストレージシステム向けONTAP 9.18.1の新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
AFX ストレージ システムで利用できるONTAP 9.18.1 に含まれる新機能について説明します。


NOTE: AFX には、ONTAP 9.18.1 で利用可能な新機能がいくつかあります。これらのうちいくつかは AFX 固有のものですが、その他多くは共通の製品基盤から派生したものです。以下に説明する AFX の機能を確認することに加えて、以下も参照してください https://docs.netapp.com/us-en/ontap/release-notes/whats-new-9181.html["ONTAP 9.18.1の新機能"^]。



[[security]]
== セキュリティ

[cols="30%,70%"]
|===
| 更新 | 説明 


 a| 
xref:../administer/additional-ontap-cluster.html[追加の管理：IPsec ハードウェアオフロード]
 a| 
IPsec ハードウェア オフロードのサポートが IPv6 に拡張されました。



 a| 
xref:../administer/additional-ontap-cluster.html[追加管理者：OpenSSL PQCアルゴリズム]
 a| 
ONTAPは、SSL向けにポスト量子コンピューティング暗号化アルゴリズムをサポートしています。これらのアルゴリズムは、将来起こり得る量子コンピューティング攻撃に対する追加の保護を提供し、SSL FIPSモードが無効になっている場合に利用できます。

|===


[[storage-resource-management-enhancements]]
== ストレージ リソース管理の機能拡張

[cols="2,4"]
|===
| 更新 | 説明 


| 強化されたボリューム配置  a| 
NetApp AFX は、クラスター内のすべてのノード間でボリュームの配置を自動的に調整します。以前のONTAPリリースでは、配置アルゴリズムはクラスタ内のボリュームの数に基づいていました。アクティビティに関係なく、すべてのノードに同じ数のボリュームが割り当てられます。 ONTAP 9.18.1 以降では、ボリュームを配置または移動するときにノードのパフォーマンスを考慮するようにアルゴリズムが強化されました。これにより、AFX クラスター内のノード間のパフォーマンスバランスが改善され、単一のノードが過負荷になる可能性が大幅に低くなります。



 a| 
xref:../administer/configure-svm.html[SVMおよびボリューム上の2レベルのネストされたQoSポリシー グループのサポート]
 a| 
QoS ポリシーを SVM と SVM 配下のボリュームに同時に割り当てることができます。

|===


[[related-information]]
== 関連情報

* https://docs.netapp.com/us-en/ontap/release-notes/index.html["ONTAP 9リリース ハイライト"^]

